stages:
    - test
    - examples

test_slurm:
    stage: test
    script: ./run_tests.sh
    tags:
            - slurm.meteo.physik.lmu.de

test_docker:
    stage: test
    image: ubuntu:rolling
    tags: 
            - docker.meteo.physik.lmu.de
    before_script:
            - apt update
            - export DEBIAN_FRONTEND=noninteractive
            - apt-get install -y libproj-dev proj-data proj-bin
            - apt-get install -y libgeos-dev
            - apt-get install -y libeccodes-dev
            - apt install -yq git vim python3 python3-pip python3-venv
    script: ./run_tests.sh

# The examples in the slurm runner are giving problems
# because cartopy wants to write into the home directory and 
# the gitlab runner does not have permissions.
#
# For now running the examples in the docker runner its enough.
# run_examples_slurm:
#     stage: examples
#     script: ./run_examples.sh
#     tags: 
#             - slurm.meteo.physik.lmu.de

run_examples_docker:
    stage: examples
    image: ubuntu:rolling
    tags: 
            - docker.meteo.physik.lmu.de
    before_script:
            - apt update
            - export DEBIAN_FRONTEND=noninteractive
            - apt-get install -y libproj-dev proj-data proj-bin
            - apt-get install -y libgeos-dev
            - apt-get install -y libeccodes-dev
            - apt install -yq git vim python3 python3-pip python3-venv
    script: ./run_examples.sh

    artifacts:
            name: example_plot_01
            paths:
                    - examples/example_plot_icon_01.png
 

